### ISSUE TITLE
Omaha 1.3.36.81 build failing

### ISSUE THREAD

**Issue by swpknl** [google/omaha#295]
Hello,
I cloned the Omaha 1.3.36.81 build, and when I tried to build the code, it was failing with the following error:
________Compiling scons-out\dbg-win\obj\goopdate\job_observer.obj
job_observer.cc
goopdate\job_observer.cc(144): error C2064: term does not evaluate to a function taking 0 arguments
goopdate\job_observer.cc(163): error C2064: term does not evaluate to a function taking 0 arguments
goopdate\job_observer.cc(173): error C2064: term does not evaluate to a function taking 0 arguments
goopdate\job_observer.cc(182): error C2064: term does not evaluate to a function taking 0 arguments
goopdate\job_observer.cc(194): error C2064: term does not evaluate to a function taking 0 arguments
goopdate\job_observer.cc(203): error C2064: term does not evaluate to a function taking 0 arguments
goopdate\job_observer.cc(213): error C2064: term does not evaluate to a function taking 0 arguments
scons: *** [scons-out\dbg-win\obj\goopdate\job_observer.obj] Error 2
scons: building terminated because of errors.

Please let me know if you need any more details.

Thanks!

**Comment by mmxw11** [comment]
Hi,

Did you try compile with Visual Studio v16.10 or newer? 16.9.8/16.9.7 seem to work fine. You can get an older version here https://docs.microsoft.com/en-us/visualstudio/releases/2019/history#installing-an-earlier-release. 

I've fixed this in https://github.com/mmxw11/omaha/commit/2d9d28e1795397cd48ac055c87f9e8f1d594c622 but compilation will still fail to "out-of-line definition for constexpr static data member is not needed and is deprecated ..." warnings. These warnings are coming from Protobuf but can be disabled by passing **/wd5041** to the compiler in [main.scons](https://github.com/google/omaha/blob/master/omaha/main.scons#L457). However, we should probably look into updating Protobuf to the latest version and hoping it's been properly fixed.

**Comment by swpknl** [comment]
Hi,

Yes, I am using Visual Studio v16.10.3. I'll downgrade to v16.9.8 and try. Thank you for your help.

**Comment by swpknl** [comment]
I can proceed further, although now the build is failing with the following error:
"C:\go/bin/go.exe" run D:\Omaha\omaha_not_working\omaha/../common/certificate_tag/certificate_tag.go -set-superfluous-cert-tag=Gact2.0Omaha -padded-length=8206 -out scons-out\dbg-win\obj\installers\GoogleUpdateSetup.exe scons-out\dbg-win\obj\installers\authenticode_GoogleUpdateSetup.exe
missing $GOPATH
scons: *** [scons-out\dbg-win\obj\installers\GoogleUpdateSetup.exe] Error 1
scons: building terminated because of errors.

I can confirm that GOPATH is defined in my environment variables. Please find the results of running "go env" below:
D:\Omaha\omaha_not_working\omaha>go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=C:\go
set GOCACHE=C:\Users\<username>\AppData\Local\go-build
set GOENV=C:\Users\<username>\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\<username>\Go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\<username>\Go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.5
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\<username>\AppData\Local\Temp\go-build2858636919=/tmp/go-build -gno-record-gcc-switches

Please let me know if any other detail is required.

**Comment by sorinj** [comment]
Regarding the Go error, I suggest using an older version of Golang. For instance, I am using go1.14.2. I recall running into a similar issue as `missing $GOPATH`, and downgrading Golang was the quickest fix. High level, I believe that the issue here is that the command line environment is not the environment that Hammer/Scons is passing to Go, because the build system is mutating the environment. Probably, a fix in the build script is needed to set `$GOPATH` correctly in the build environment.

**Comment by swpknl** [comment]
Thank you for the prompt response. I can build the code successfully after using a lower version of Go.

Thanks!
